### PR TITLE
edited get_marc856 to handle $sign in URL. Also removed a print state…

### LINKED ISSUE #1096: handle dollar sign in URL string for HathiTrust
Found that some HathiTrust handles use the '$' character. This Voyager catalog title, Bullfinch's Mythology, http://catalog.wrlc.org/cgi-bin/Pwebrecon.cgi?BBID=14779127 has the full link, http://hdl.handle.net/2027/uc1.$b115538

Problem: Our JSON element ELECTRONIC_DATA:LINK856U has the full link, however element MFHD_DATA.marc856list.u and element ONLINE.url stop at the $ symbol, leaving incomplete link 
"http://hdl.handle.net/2027/uc1."

### PR DESCRIPTION
**Pull request by cummingsm**
…ment. Fixes #1096

### CODE REVIEW

**Comment by lwrubel** [comment]
Suggest correcting indent of lines 860-862 to 4 spaces, for [PEP8](https://www.python.org/dev/peps/pep-0008/) compliance.

What if there is a subfield other than 3,u,z in the 856, such as $x? Will it get joined to the $u?

**Comment by lwrubel** [comment]
BTW, I've also send HathiTrust a question about this. It seems like a mistake to have a $ in a URL,  particularly since it's not consistent with most other handle URLs in their catalog.

**Comment by cummingsm** [comment]
Laura,

It seems that it is not all that unusual for the HathiTrust links to
include dollar signs. Here are some more examples.


uhttp://hdl.handle.net/2027/mdp.35112104302791zClick here for access to
e-publication.
uhttp://hdl.handle.net/2027/loc.ark:/13960/t2d79qd6vzClick here for
access to e-publication.
uhttp://hdl.handle.net/2027/hvd.32044084789833zClick here for access to
e-publication.
uhttp://hdl.handle.net/2027/uc1.b4348899zClick here for access to
e-publication.
uhttp://hdl.handle.net/2027/uc1.$b95584zClick here for access to
e-publication.
uhttp://hdl.handle.net/2027/uc1.$b320109zClick here for access to
e-publication.
uhttp://hdl.handle.net/2027/uc1.$b116831zClick here for access to
e-publication.
uhttp://hdl.handle.net/2027/uc1.$b670784zClick here for access to
e-publication.
uhttp://hdl.handle.net/2027/uc1.$b115538zClick here for access to
e-publication.
uhttp://hdl.handle.net/2027/uc1.$b587607zClick here for access to
e-publication.



Thanks,

*Mike *

**Comment by lwrubel** [comment]
I'm only seeing the $ in the uc1 examples. Am I missing something?

**Comment by cummingsm** [comment]
Maybe the 'uc' links are the only ones with the dollar sign in the URL. But there are many.

**Comment by lwrubel** [comment]
Right, I agree about that, and we do need to handle them, even though it
seems inconsistent with the rest of HathiTrust handle URLs.

**Comment by cummingsm** [comment]
Updated for PEP8 per LW suggestion. Also, searched for e-resource holdings, 856 tags having subfields other than 3, u, z. Couldn't find any.

**Comment by lwrubel** [comment]
There should be some with $x. E-resources and RDG uses that to preserve a vendor URL when a findit URL is put in place for an ejournal or ebook. It's also used as a record when a vendor URL is changed or needing to be retained for some other reason. I'm trying to dig up an example or two. This MFHD attached to this bibid may be suppressed: 7473776.

**Comment by cummingsm** [comment]
OK, I wasn't aware of that practice, and didn't come across any like that in my search.  I've revised the branch to exclude the contents of subfield x.

**Pull request merged**
